[WIP] Fixed some Travis CI stuff

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -26,12 +26,12 @@ script:
     - FORCE_REBUILD=yes ./build.sh
     - for debug in 'yes' 'no'; do
           for toolchain in 'gcc' 'generic' 'clang'; do
-              echo "Testing toolchain '${toolchain}', debug=${debug}"
+              echo "Testing toolchain '${toolchain}', debug=${debug}";
               if ! CC_TOOLCHAIN="${toolchain}" DEBUG="${debug}" FORCE_REBUILD=yes ./build.sh; then
-                  echo "Failed"
-                  exit 1
-              else
-          done
+                  echo "Failed";
+                  exit 1;
+              fi;
+          done;
       done
     - echo "Testing custom toolchain"
     - CUSTOM_CC='/usr/bin/cc' CUSTOM_CXX='/usr/bin/c++' CUSTOM_LD='c++' CC_TOOLCHAIN='custom' FORCE_REBUILD='yes' DEBUG='yes' ./build.sh
